### ISSUE TITLE
implement group rpc

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis-accounts#40] opened 2020-06-19 15:34 UTC
while ocis-accounts now persists users it also needs to persist groups.

It should follow the implementation for the users, which in turn was built with a look at the ms graph api.
- [x] define  group properties and rpcs in account.proto
- [ ] implement rpc calls
  - [ ] ListGroups
  - [ ] GetGroup
  - [ ] CreateGroup
  - [ ] UpateGroup
  - [ ] DeleteGroup
  - [ ] AddMember
  - [ ] Remove Member
  - [ ] ListMembers

see the accounts.proto file for additional links, eg 

Open design questions:

Currently we treat group and users as twe resources. Users currently only have the `gid_number` property which I added to satisfy ldap queries that an os or eos will make to determine acls and permissions. For additional groups a user is a member of it will make additional ldap queries, eg get all groups the user is a member of. Since that is done via ldap we can leave fetching this information  to ocis-glauth.

In the current protobuf an account has a `memberOf` property, which is a list of groups ... we can fill that ... but it might become a lot of groups. We could opt to not return the groups by default but only if they are included in the [field mask](https://medium.com/google-cloud/building-apis-with-grpc-continued-f53b5a5ab850).

**Comment by micbar** [comment] 2020-06-22 11:19
Duplicate of https://github.com/owncloud/product/issues/68

**Closed by micbar** 2020-06-22 11:19 UTC
